# Generated by Django 2.0.1 on 2018-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('modalidad', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_inicio', models.CharField(max_length=100)),
                ('fecha_fin', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
