# Generated by Django 2.0.1 on 2018-01-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('CONF', 'Conferencia'), ('SEMI', 'Seminario'), ('CONG', 'Congreso'), ('CURS', 'Curso')], max_length=100),
        ),
    ]
