# Generated by Django 2.0.1 on 2018-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto0', '0002_auto_20180131_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modalidad',
            field=models.CharField(choices=[('PRES', 'Presencial'), ('VIRT', 'Virtual')], max_length=100),
        ),
    ]
