# Generated by Django 2.0.1 on 2018-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto0', '0006_auto_20180203_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
